backend_url = "http://localhost:4000"
#[ProjectOwner,Member,TaskCreator,TaskAssignee,admin]

[[permissions]] #UNTESTED
path = "/api/v2/users"
method = "GET"
allowed_roles = ["*"]

[[permissions]] #TESTED pjowner,pjmember,admin,outsider
path = "/api/v2/projects"
method = "GET"
allowed_roles = ["*"]

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/projects"
method = "POST"
allowed_roles = ["*"]

[[permissions]] #TESTED pjowner,pjmember,admin,outsider
path = "/api/v2/projects/:project_id"
method = "GET"
allowed_roles = ["ProjectOwner","Member"]
param = "project_id"

[[permissions]] #TESTED pjowner,admin,outsider
path = "/api/v2/projects/:project_id"
method = "PATCH"
allowed_roles = ["ProjectOwner"]
param = "project_id"

[[permissions]] #TESTED pjowner,admin,outsider
path = "/api/v2/projects/:project_id"
method = "DELETE"
allowed_roles = ["ProjectOwner"]
param = "project_id"

[[permissions]] #TESTED pjowner,pjmember,admin,outsider
path = "/api/v2/projects/tag/:tag_id"
method = "POST"
allowed_roles = ["ProjectOwner"]
param = "tag_id"

[[permissions]] #TESTED pjowner,pjmember,admin,outsider
path = "/api/v2/projects/tag/:tag_id"
method = "DELETE"
allowed_roles = ["ProjectOwner"]
param = "tag_id"

[[permissions]] #UNTESTED
path = "/api/v2/projects/pin/:project_id"
method = "POST"
allowed_roles = ["*"]
param = "tag_id"

[[permissions]] #UNTESTED
path = "/api/v2/projects/pin/:project_id"
method = "DELETE"
allowed_roles = ["*"]
param = "tag_id"

[[permissions]] #UNTESTED
path = "/api/v2/projects/owner"
method = "PATCH"
allowed_roles = ["ProjectOwner"]

[[permissions]] 
path = "/api/v2/projects/assign/:project_id"
method = "POST"
allowed_roles = ["ProjectOwner"]
param = "project_id"

[[permissions]]
path = "/api/v2/projects/assign/:project_id"
method = "DELETE"
allowed_roles = ["ProjectOwner"]
param = "project_id"













[[permissions]]
path = "/api/v2/tasks/:id"
method = "GET"
allowed_roles = ["TaskCreator", "ProjectOwner", "TaskAssignee"]
param = "id"
