backend_url = "http://localhost:4000"

[[permissions]]
path = "/api/v2/users"
method = "GET"
allowed_roles = ["admin"]

[[permissions]]
path = "/api/v2/projects/:project_id"
method = "GET"
allowed_roles = ["ProjectOwner"]
param = "project_id"

[[permissions]]
path = "/api/v2/tasks/:id"
method = "PATCH"
allowed_roles = ["admin", "ProjectOwner"]
param = "id"