backend_url = "http://prod-app:4000"
#[ProjectOwner,Member,TaskCreator,TaskAssignee,admin]

[[permissions]] #TESTED pjowner, member, taskcreator, taskassignee, admin, outsider
path = "/api/v2/comments/:id"
method = "GET"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee"]
param = "id"

[[permissions]] #TESTED
path = "/api/v2/comments/:id"
method = "DELETE"
allowed_roles = ["*"]
param = "id"

[[permissions]] #TESTED
path = "/api/v2/comments/:id"
method = "PATCH"
allowed_roles = ["*"]
param = "id"

[[permissions]] #NOT PASSED, should have param taskId
path = "/api/v2/comments/:id"
method = "POST"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee"]
param = "id"