backend_url = "http://prod-app:4000"
#[ProjectOwner,Member,TaskCreator,TaskAssignee,admin]

[[permissions]] #NOT PASSED, should have param taskId
path = "/api/v2/file/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #NOT PASSED, should have param taskId
path = "/api/v2/file/:id"
method = "POST"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee"]
param = "id"

[[permissions]] #NOT PASSED, should have param taskId
path = "/api/v2/file/:id"
method = "DELETE"
allowed_roles = ["ProjectOwner", "TaskCreator"]
param = "id"

[[permissions]] #TESTED pjowner, member, taskcreator, taskassignee, admin, outsider
path = "/api/v2/activities/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #TESTED
path = "/api/v2/template/"
method = "GET"
allowed_roles = ["*"]

[[permissions]] #TESTED
path = "/api/v2/template/:id"
method = "POST"
allowed_roles = ["ProjectOwner"]
param = "id"

[[permissions]] #TESTED
path = "/api/v2/template/"
method = "DELETE"
allowed_roles = ["admin"]

[[permissions]] #TESTED
path = "/api/v2/template/"
method = "PATCH"
allowed_roles = ["admin"]

[[permissions]] #TESTED
path = "/api/v2/ganttchart/project"
method = "GET"
allowed_roles = ["admin", "head"]

[[permissions]] #TESTED
path = "/api/v2/ganttchart/:id"
method = "GET"
allowed_roles = ["admin", "head"]
param = "id"

[[permissions]] #TESTED
path = "/api/v2/dashboard/project"
method = "GET"
allowed_roles = ["admin"]

[[permissions]] #TESTED
path = "/api/v2/dashboard/project/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #TESTED
path = "/api/v2/dashboard/workload"
method = "GET"
allowed_roles = ["admin","head"]

[[permissions]] #TESTED
path = "/api/v2/dashboard/workload/:id"
method = "GET"
allowed_roles = ["admin","head"]
param = "id"


