backend_url = "http://prod-app:4000"
#[ProjectOwner,Member,TaskCreator,TaskAssignee,admin]

[[permissions]] #TESTED 
path = "/api/v2/tags"
method = "GET"
allowed_roles = ["*"]

[[permissions]] #TESTED 
path = "/api/v2/tags/:id"
method = "DELETE"
allowed_roles = ["admin"]
param = "id"

[[permissions]] #TESTED 
path = "/api/v2/tags/:id"
method = "PATCH"
allowed_roles = ["admin"]
param = "id"

[[permissions]] #TESTED 
path = "/api/v2/tags"
method = "POST"
allowed_roles = ["admin"]

[[permissions]] #TESTED
path = "/api/v2/tags/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #TESTED
path = "/api/v2/tags/getassigntag/:taskId"
method = "GET"
allowed_roles = ["*"]
param = "taskId"

[[permissions]] #TESTED
path = "/api/v2/tags/getassigntask/:tagId"
method = "GET"
allowed_roles = ["*"]
param = "tagId"

[[permissions]] #TESTED
path = "/api/v2/tags/assign/:taskId"
method = "POST"
allowed_roles = ["ProjectOwner", "TaskCreator"]
param = "taskId"

[[permissions]] #TESTED
path = "/api/v2/tags/unassigned/:taskId"
method = "DELETE"
allowed_roles = ["ProjectOwner", "TaskCreator"]
param = "taskId"
