backend_url = "http://prod-app:4000"
#[ProjectOwner,Member,TaskCreator,TaskAssignee,admin]

[[permissions]] #TESTED admin, not admin
path = "/api/v2/tasks/"
method = "GET"
allowed_roles = ["admin"]

[[permissions]] #TESTED pjowner, member, outsider
path = "/api/v2/tasks/:id"
method = "POST"
allowed_roles = ["ProjectOwner", "Member", "head"]
param = "id"

[[permissions]] #TESTED pjowner, member, outsider
path = "/api/v2/tasks/duplicateTask/:id"
method = "POST"
allowed_roles = ["ProjectOwner", "Member", "head"]
param = "id"

[[permissions]] #TESTED pjowner, member, outsider
path = "/api/v2/tasks/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #TESTED pjowner, member, outsider
path = "/api/v2/tasks/:id"
method = "DELETE"
allowed_roles = ["ProjectOwner", "TaskCreator", "head"]
param = "id"

[[permissions]] #TESTED pjowner, member, outsider
path = "/api/v2/tasks/:id"
method = "PATCH"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee", "head"]
param = "id"

[[permissions]] #TESTED pjowner, member, outsider
path = "/api/v2/tasks/user/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #IS IT USED?
path = "/api/v2/tasks/project/:projectid"
method = "GET"
allowed_roles = ["*"]
param = "projectid"

[[permissions]] #IS IT USED?
path = "/api/v2/tasks/child/:parentid"
method = "GET"
allowed_roles = ["*"]
param = "parentid"

[[permissions]] #TESTED pjowner, admin, outsider
path = "/api/v2/tasks/template/:id"
method = "POST"
allowed_roles = ["ProjectOwner", "head"]
param = "id"

[[permissions]] #TESTED pjowner, admin, outsider
path = "/api/v2/tasks/assign/:taskId"
method = "POST"
allowed_roles = ["ProjectOwner", "TaskCreator", "head"]
param = "taskId"

[[permissions]] #TESTED pjowner, admin, outsider
path = "/api/v2/tasks/unassigned/:taskId"
method = "DELETE"
allowed_roles = ["ProjectOwner", "TaskCreator", "head"]
param = "taskId"

[[permissions]] #TESTED pjowner, admin, outsider
path = "/api/v2/tasks/status/:taskId"
method = "PATCH"
allowed_roles = ["*"]
param = "taskId"


[[permissions]] #TESTED pjowner, admin, outsider, taskassignee
path = "/api/v2/tasks/emoji/:taskId"
method = "POST"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee", "head"]
param = "taskId"


[[permissions]] #TESTED pjowner, admin, outsider, taskassignee
path = "/api/v2/tasks/emoji/:taskId"
method = "PATCH"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee", "head"]
param = "taskId"

[[permissions]] #TESTED pjowner, admin, outsider, taskassignee
path = "/api/v2/tasks/emoji/:taskId"
method = "GET"
allowed_roles = ["*"]
param = "taskId"

[[permissions]] #TESTED pjowner, admin, outsider, taskassignee
path = "/api/v2/tasks/parent-recursive/:taskId"
method = "GET"
allowed_roles = ["*"]
param = "taskId"

[[permissions]] #TESTED pjowner, admin, outsider, taskassignee
path = "/api/v2/tasks/parent/:taskId"
method = "GET"
allowed_roles = ["*"]
param = "taskId"

[[permissions]] #TESTED pjowner, admin, outsider, taskassignee
path = "/api/v2/tasks/money/:taskId"
method = "POST"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee","head"]
param = "taskId"

[[permissions]] #TESTED pjowner, admin, outsider, taskassignee
path = "/api/v2/tasks/money/:taskId"
method = "DELETE"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee","head"]
param = "taskId"

[[permissions]] #UNTESTED
path = "/api/v2/tasks/date/:taskId"
method = "PATCH"
allowed_roles = ["ProjectOwner", "TaskCreator", "TaskAssignee","head"]
param = "taskId"
