backend_url = "http://prod-app:4000"
#[ProjectOwner,Member,TaskCreator,TaskAssignee,admin]

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/users"
method = "GET"
allowed_roles = ["*"]

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/users"
method = "POST"
allowed_roles = ["admin"]

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/users/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/users/role/:id"
method = "PATCH"
allowed_roles = ["admin"]
param = "id"

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/users/activate/:id"
method = "PATCH"
allowed_roles = ["admin"]
param = "id"

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/users/email/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"

[[permissions]] #TESTED admin,notadmin
path = "/api/v2/users/project/:id"
method = "GET"
allowed_roles = ["*"]
param = "id"